In [1]:
import cupy

In [2]:
import numba

In [3]:
import pycuda

In [4]:
import cupy as cp

In [5]:
x = cp.arange(6).reshape(2, 3).astype('f')
x
#array([[ 0.,  1.,  2.],
#       [ 3.,  4.,  5.]], dtype=float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [6]:
x.sum(axis=1)
#array([  3.,  12.], dtype=float32)

array([ 3., 12.], dtype=float32)